#ifndef CarVars_h
#define CarVars_h

#define SERVO_PIN 8
#define ESC_PIN 9

#define US_REAR_ADDRESS 0x73
#define US_FRONT_ADDRESS 0x70

#define US_GAIN 0x1F //maximum gain
#define US_RANGE 0x07 //7 for 34 centimeters

#define IR_REAR_LEFT_PIN A1
#define IR_REAR_RIGHT_PIN A2
#define IR_MIDDLE_REAR_PIN A0
#define IR_MIDDLE_FRONT_PIN A3

#define ENCODER_LEFT_PIN 2
#define ENCODER_RIGHT_PIN 3

#define OVERRIDE_SIGNAL_PIN A9
#define OVERRIDE_THROTTLE_PIN A8
#define OVERRIDE_SERVO_PIN A10

#define OVERRIDE_SIGNAL_AVERAGE_FREQ 790
#define OVERRIDE_SIGNAL_TOLERANCE 10

#define THROTTLE_SIGNAL_IDLE_FREQ 1500
#define THROTTLE_SIGNAL_TOLERANCE 100

#define NEUTRAL_FREQUENCY 1500
#define OVERRIDE_FORWARD_SPEED 60
#define OVERRIDE_BACKWARD_SPEED -250
#define OVERRIDE_STEER_RIGHT 20
#define OVERRIDE_STEER_LEFT -20
#define OVERRIDE_FREQ_TOLERANCE 200

#endif
